"""Parse department-generated supervised handoff proposals."""

from __future__ import annotations

from dataclasses import dataclass
import json
from typing import Any

from curvature_console.infrastructure.handoff import DEPARTMENT_IDS


BEGIN_MARKER = "BEGIN_CURVATURE_HANDOFF_PROPOSAL"
END_MARKER = "END_CURVATURE_HANDOFF_PROPOSAL"
SCHEMA_VERSION = 1


class HandoffProposalError(ValueError):
    """Raised when a proposed handoff block is malformed or unsafe."""


@dataclass(frozen=True, slots=True)
class HandoffProposal:
    """One validated proposal generated by a source department."""

    target_department_id: str
    title: str
    reason: str
    task: str
    relevant_context: str
    expected_output: str
    acceptance_criteria: tuple[str, ...]

    def render_visible_message(self) -> str:
        """Render the structured proposal for user review and delivery."""

        criteria = "\n".join(
            f"- {criterion}" for criterion in self.acceptance_criteria
        )
        return "\n\n".join(
            (
                f"# {self.title}",
                f"## Reason for handoff\n{self.reason}",
                f"## Task\n{self.task}",
                f"## Relevant context\n{self.relevant_context}",
                f"## Expected output\n{self.expected_output}",
                f"## Acceptance criteria\n{criteria}",
            )
        )


@dataclass(frozen=True, slots=True)
class HandoffProposalParseResult:
    """All valid proposals plus bounded diagnostics for rejected blocks."""

    proposals: tuple[HandoffProposal, ...]
    errors: tuple[str, ...]


def parse_handoff_proposals(
    response_text: str,
    *,
    source_department_id: str,
) -> HandoffProposalParseResult:
    """Parse all delimited proposal blocks from one assistant response."""

    if source_department_id not in DEPARTMENT_IDS:
        raise HandoffProposalError(
            f"Unknown source department: {source_department_id!r}."
        )

    proposals: list[HandoffProposal] = []
    errors: list[str] = []
    cursor = 0
    block_number = 0

    while True:
        begin = response_text.find(BEGIN_MARKER, cursor)
        if begin < 0:
            break
        block_number += 1
        body_start = begin + len(BEGIN_MARKER)
        end = response_text.find(END_MARKER, body_start)
        if end < 0:
            errors.append(
                f"Proposal block {block_number}: missing {END_MARKER}."
            )
            break

        raw_body = response_text[body_start:end].strip()
        cursor = end + len(END_MARKER)
        try:
            payload = json.loads(raw_body)
            proposals.append(
                _proposal_from_payload(
                    payload,
                    source_department_id=source_department_id,
                )
            )
        except (json.JSONDecodeError, HandoffProposalError) as exc:
            errors.append(f"Proposal block {block_number}: {exc}")

    return HandoffProposalParseResult(
        proposals=tuple(proposals),
        errors=tuple(errors),
    )


def _proposal_from_payload(
    payload: Any,
    *,
    source_department_id: str,
) -> HandoffProposal:
    if not isinstance(payload, dict):
        raise HandoffProposalError("JSON root must be an object.")

    if payload.get("schema_version") != SCHEMA_VERSION:
        raise HandoffProposalError(
            f"schema_version must be {SCHEMA_VERSION}."
        )

    target = _required_text(payload, "target_department_id")
    if target not in DEPARTMENT_IDS:
        raise HandoffProposalError(
            f"Unknown target_department_id: {target!r}."
        )
    if target == source_department_id:
        raise HandoffProposalError(
            "Source and target departments must be different."
        )

    criteria_value = payload.get("acceptance_criteria")
    if not isinstance(criteria_value, list) or not criteria_value:
        raise HandoffProposalError(
            "acceptance_criteria must be a non-empty JSON array."
        )
    criteria = tuple(
        _clean_list_item(item, "acceptance_criteria")
        for item in criteria_value
    )

    return HandoffProposal(
        target_department_id=target,
        title=_required_text(payload, "title"),
        reason=_required_text(payload, "reason"),
        task=_required_text(payload, "task"),
        relevant_context=_required_text(payload, "relevant_context"),
        expected_output=_required_text(payload, "expected_output"),
        acceptance_criteria=criteria,
    )


def _required_text(payload: dict[str, Any], key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise HandoffProposalError(f"{key} must be a non-empty string.")
    return value.strip()


def _clean_list_item(value: Any, key: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise HandoffProposalError(
            f"Every {key} item must be a non-empty string."
        )
    return value.strip()
